### ISSUE TITLE
Bluetooth keeps stopping

### ISSUE THREAD

**Issue by Smiley-official** [open-android/Android#71]
Hello, I rooted my phone and wiped all data and now bluetooth not working. First error was "SQLite can't open database "/user_de/0/com.android.bluetooth/databases doesnt exist" (but it existed). I reinstalled bluetooth and got this error:
`java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libbluetooth_qti_jni.so" needed or dlopened by "/apex/com.android.art/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
	at java.lang.System.loadLibrary(System.java:1664)
	at com.android.bluetooth.btservice.AdapterApp.<clinit>(AdapterApp.java:39)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1159)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1240)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6957)
	at android.app.ActivityThread.access$1600(ActivityThread.java:257)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1993)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)`
What i need to do?

**Comment by developmans** [comment]
已收到！

**Comment by CasterXzs** [comment]
已收到您的邮件，稍后我将浏览，如有疑问，可私聊，谢谢！

**Comment by Smiley-official** [comment]
> 已收到您的邮件，稍后我将浏览，如有疑问，可私聊，谢谢！

謝謝你，我會等!

**Comment by Smiley-official** [comment]
(Google translate)
